### ISSUE TITLE
Reboot after successful run.

### ISSUE THREAD

**Issue by anttitai** [pkerspe/ESP-StepperMotor-Server-UI#7] opened 2020-07-05 09:02 UTC
After run  I'll get following information : 

Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0xfefefefe  PS      : 0x00060b30  A0      : 0x800d944a  A1      : 0x3ffdb810  
A2      : 0xfefefefe  A3      : 0x00000001  A4      : 0x00001388  A5      : 0x00001388
A6      : 0x00000003  A7      : 0x00060023  A8      : 0x8014d620  A9      : 0x3ffdb7f0  
A10     : 0x02000000  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000001
A14     : 0x00000000  A15     : 0x3ffd91e0  SAR     : 0x00000007  EXCCAUSE: 0x00000014  
EXCVADDR: 0xfefefefc  LBEG    : 0x400029ac  LEND    : 0x400029cb  LCOUNT  : 0x00000000  

Backtrace: 0x7efefefe:0x3ffdb810 0x400d9447:0x3ffdb830 0x40088e99:0x3ffdb850

**Decoded results:**
Decoding stack results
0x400d9447: ESPStepperMotorServer_MotionController::processMotionUpdates(void*) at \ESP-StepperMotor-Server\src\ESPStepperMotorServer_MotionController.cpp line 76
0x40088e99: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143

Rebooting...

Edit:changed to https://github.com/pkerspe/ESP-StepperMotor-Server

**Comment by pkerspe** [comment] 2020-07-05 11:46
Hello @anttitai
 A assume your compiling in Arduino IDE. Since it does not manage dependencies properly you might probably be using the master branch version of the ESP-FlexyStepper library.
The issue you describe is probably only occurring when you start moving the stepper motor, right?
If so, you should install ESP-FlexyStepper version 1.2 and not the last version from master branch.
The master branch is currently in a state that has issues with new features.
Please provide more details if the issue persists after installing ESP-FLexyStepper 1.2

In general I recommend using a proper IDE that can manager dependencies a bit better than Arduino IDE, I suggest taking a look into PlatformIO. Takes only minutes to install and get ready to go and has way more features than Arduino IDE. But that is just a side note, once you update the Library version of ESP-FlexyStepper you should be able to run it also using the Arduino compiled code

**Comment by pkerspe** [comment] 2020-07-05 11:50
closing this here, since it is a duplicate of the issue in ESP-StepperMotor-Server

**Closed as completed by pkerspe** 2020-07-05 11:50 UTC

**Comment by anttitai** [comment] 2020-07-05 11:59
I'm using platformio. Problem solved after moving to ESP-FLexyStepper 1.2 . Now it'sOK.  
Previous problem came every time  just after the motor stopped.
